name: Publish to NuGet

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: 
      name: "Publish Release"
      url: https://www.nuget.org/packages/Markdown.ColorCode/
    steps:
    - uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x

    - name: Restore Dependencies
      run: dotnet restore src

    - name: Build
      run: dotnet build src --configuration Release --no-restore
      
    - name: Publish NuGet
      uses: alirezanet/publish-nuget@v3.1.0
      with:
        PROJECT_FILE_PATH: src/Markdown.ColorCode/Markdown.ColorCode.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish NuGet
      uses: alirezanet/publish-nuget@v3.1.0
      with:
        PROJECT_FILE_PATH: src/Markdown.ColorCode.CSharpToColoredHtml/Markdown.ColorCode.CSharpToColoredHtml.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
